services:
  ggwp-host:
    build: .
    container_name: ggwp-host
    cap_add:
      - SYS_PTRACE
    env_file:
      - path: .env
        required: false
    ports:
      - "${GGWP_SSH_PORT:-2222}:22"
      - "80:80"
      - "443:443"
    volumes:
      - ./container/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./container/entrypoint.sh:/entrypoint.sh
      - ./container/create-user.sh:/create-user.sh
      - ./container/tinker.sh:/tinker.sh
      - ./container/update_nginx_tunnel_map.sh:/update_nginx_tunnel_map.sh
      - ./data:/var/ggwp/data
